import type Cube from '@rubiks/core';

export default function drawCube(canvas: HTMLCanvasElement, cube: Cube) {
  const context = canvas.getContext('2d')!;

  context.strokeStyle = 'black';

  context.setTransform(1, 0, -1, 1, 0, 0);
  context.beginPath();
  context.fillStyle = cube.sides.up[0][0];
  context.rect(132, 45, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.up[0][1];
  context.rect(147, 45, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.up[0][2];
  context.rect(162, 45, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.up[1][0];
  context.rect(132, 55, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.up[1][1];
  context.rect(147, 55, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.up[1][2];
  context.rect(162, 55, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.up[2][0];
  context.rect(132, 65, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.up[2][1];
  context.rect(147, 65, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.up[2][2];
  context.rect(162, 65, 15, 10);
  context.fill();
  context.stroke();
  context.closePath();

  context.setTransform(1, 0, 0, 1, 0, 0);
  context.beginPath();
  context.fillStyle = cube.sides.left[0][0];
  context.rect(12, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.left[0][1];
  context.rect(27, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.left[0][2];
  context.rect(42, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.left[1][0];
  context.rect(12, 90, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.left[1][1];
  context.rect(27, 90, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.left[1][2];
  context.rect(42, 90, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.left[2][0];
  context.rect(12, 105, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.left[2][1];
  context.rect(27, 105, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.left[2][2];
  context.rect(42, 105, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.front[0][0];
  context.rect(57, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.front[0][1];
  context.rect(72, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.front[0][2];
  context.rect(87, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.front[1][0];
  context.rect(57, 90, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.front[1][1];
  context.rect(72, 90, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.front[1][2];
  context.rect(87, 90, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.front[2][0];
  context.rect(57, 105, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.front[2][1];
  context.rect(72, 105, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.front[2][2];
  context.rect(87, 105, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.setTransform(1, -1, 0, 1, 0, 0);
  context.beginPath();
  context.fillStyle = cube.sides.right[0][0];
  context.rect(102, 177, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.right[0][1];
  context.rect(112, 177, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.right[0][2];
  context.rect(122, 177, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.right[1][0];
  context.rect(102, 192, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.right[1][1];
  context.rect(112, 192, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.right[1][2];
  context.rect(122, 192, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.right[2][0];
  context.rect(102, 207, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.right[2][1];
  context.rect(112, 207, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.right[2][2];
  context.rect(122, 207, 10, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.setTransform(1, 0, 0, 1, 0, 0);
  context.beginPath();
  context.fillStyle = cube.sides.back[0][0];
  context.rect(132, 45, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.back[0][1];
  context.rect(147, 45, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.back[0][2];
  context.rect(162, 45, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.back[1][0];
  context.rect(132, 60, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.back[1][1];
  context.rect(147, 60, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.back[1][2];
  context.rect(162, 60, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.back[2][0];
  context.rect(132, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.back[2][1];
  context.rect(147, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.back[2][2];
  context.rect(162, 75, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.down[0][0];
  context.rect(57, 120, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.down[0][1];
  context.rect(72, 120, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.down[0][2];
  context.rect(87, 120, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.down[1][0];
  context.rect(57, 135, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.down[1][1];
  context.rect(72, 135, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.down[1][2];
  context.rect(87, 135, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();

  context.beginPath();
  context.fillStyle = cube.sides.down[2][0];
  context.rect(57, 150, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.down[2][1];
  context.rect(72, 150, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
  context.beginPath();
  context.fillStyle = cube.sides.down[2][2];
  context.rect(87, 150, 15, 15);
  context.fill();
  context.stroke();
  context.closePath();
}
